# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d34f6358c4d3de44fc5ec357aa921c2e2441d4f226f59dbfceca934fda2402cb8400fe2606991ab53834de582f52b8c8e5daa8e3532fe7590bf01d6ed1cced6

test:
  secret_key_base: 6f5c360083d98d45296d112ec54f20f9f3aa1e7df1ec1147fc3d06aa9e5609834bc8f535931eab3c4403161d936b05c3d192546388d359579310a3361eac4b31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
